version: '3.7'
services:
  config-server:
    image: config-server:v1
    ports:
      - "8888:8888"
    restart: always
    networks:
      - springcloud
  eureka-server:
    image: eureka-server:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud
  mysql8:
    image: mysql:8
    ports:
      - "3306:3306"
    restart: always
    networks:
      - springcloud
    environment: 
      MYSQL_DATABASE: db_springboot_cloud
      MYSQL_ROOT_PASSWORD: 1234
  postgres12:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: always
    networks:
      - springcloud
    environment: 
      POSTGRES_DB: db_springboot_cloud
      POSTGRES_PASSWORD: 1234
  products-service:
    image: products-service:v1
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - mysql8
  items-service:
    image: items-service:v1
    ports:
      - "8002:8002"
      - "8005:8005"
      - "8007:8007"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - products-service
   users-service:
    image: users-service:v1
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - postgres12
   oauth-server:
    image: oauth-server:v1
    ports:
      - "9100:9100"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - users-service
  zuul-server:
    image: zuul-server:v1
    ports:
      - "8090:8090"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - products-service
      - items-service
      - users-service
      - oauth-server
  rabbitmq38:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - springcloud
  zipkin-server:
    image: zipkin-server:v1
    ports:
      - "9411:9411"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - rabbitmq38
      - mysql8
    environment: 
      RABBIT_ADDRESSES: microservicios-rabbitmq38:5672
      STORAGE_TYPE: mysql
      MYSQL_USER: zipkin
      MYSQL_PASS: zipkin
      MYSQL_HOST: mysql8
networks:
  springcloud: